### ISSUE TITLE
How secure is the docker-compose approach?

### ISSUE THREAD

**Issue by dheil** [pinterest/snappass#117]
Hi,

the following warning shows up when i start the docker container:

> WARNING: This is a development server. Do not use it in a production deployment.

How 'true' or dangerous is that warning?

I am not familiar with Python Webservers - so should i use another one than flask?

I want to run that project in a publicly accessible (but of course SSL secured) docker-container and have also provided a 'SECRET_KEY'.

Can the public accessibility really be a problem?

**Comment by devinlundberg** [comment]
Assuming the you also have not set the DEBUG env variable, you should be ok from an integrity and confidentiality perspective. 

That warning is about availability and its from Flask. Flask's built in server only uses a single thread for serving requests so your server will not handle be able to handle requests in parallel. See https://github.com/pallets/flask/issues/3168 and https://vsupalov.com/flask-web-server-in-production/ for more information

**Comment by dheil** [comment]
No, i didn't activate the debug option. So i should be fine :)
 
Thank you! 👍
