### ISSUE TITLE
feature request: Prevent crawler from opening / invalidate secret

### ISSUE THREAD

**Issue by akappler** [pinterest/snappass#125]
Now a days many are using Slack, Teams, Skype, ... or similar tools. Unfortunatly you can't send the link to e.g. co-works via these tools as they try to generate a preview of the page and therefore opens the link. This leads to an invalid secret. 

My suggestions are: 
1) Add a button which will decode the secret - or something similar
2) Optional user can enter a password

I guess I'd go for #1 but #2 would be fine as well.

In the end it would be awesome to safely send credentials/secrets also via messengers.

**Comment by Kav7** [comment]
This has been resolved with later releases

**Comment by jparise** [comment]
Yes, this was addressed by #100.
