### ISSUE TITLE
Question about creation of multiple links

### ISSUE THREAD

**Issue by cecio** [pinterest/snappass#136]
Hello.

I often have the need to create 2-3 links for the same password, if I need to share it with more people. Right now I have to make the procedure multiple times.

I'm implementing a little mod to add a "# of links" field (just below the ttl), so that the resulting page will show me all the links that I can C&P somewhere else. 
Are you interested in a pull request?

Thanks,

**Comment by cecio** [comment]
May be I add a couple of screenshot to make it more clear :-)

![image](https://user-images.githubusercontent.com/10587300/106780756-99dce080-6648-11eb-9571-993738134499.png)


![image](https://user-images.githubusercontent.com/10587300/106780654-803b9900-6648-11eb-97bd-c014b0b7047b.png)

**Comment by jparise** [comment]
This hasn't come up before, but it does sound like it could be useful. I suspect most people that have the need for multiple links just go through the process multiple times, as you note.

If we were to implement this, we'd want to put some upper bound (e.g. 5?) on the number of links that could be created, so the usefulness of this feature would be capped at that number. For other "bulk" creation cases, something like the API proposed in #51 would be a better fit.

**Comment by cecio** [comment]
I totally agree with you, we can cap it to a relatively low number. Higher numbers require automation.

**Comment by cecio** [comment]
OK, so if you think it's useful, I'll go ahead in clean it up a bit and I'll make a pull request.

**Comment by jparise** [comment]
Sorry for the delay, and thanks for sending along the proposed changes in #137.

For the moment, our preference is to keep the system and its code simple and focused on vending a single link at a time. The "multiple links" use case hasn't come up very often, and there is a manual "workaround" for the times when it does.

Limiting the number of features we provide makes this project easier to maintain and audit, given that it is a security product.

**Comment by cecio** [comment]
OK, I understand your point, no problem.
Thanks,
