### ISSUE TITLE
Any way to change the URL of the links that the Docker Container SnapPass spits out?

### ISSUE THREAD

**Issue by azaloum90** [pinterest/snappass#140]
My URL's are coming out like this:
https://127.0.0.1:5000/snappass1efcf95601c744f8990eb626c4ee4c9d~bkwAN0ASluTkN1BBjsI8NYsAYSuUjcUyeiC8MPjrs9Y%3D

but I need them to come out like this:
https://snappass.atozcc.net/snappass1efcf95601c744f8990eb626c4ee4c9d~bkwAN0ASluTkN1BBjsI8NYsAYSuUjcUyeiC8MPjrs9Y%3D

I already have the reverse proxy working, and if I manually swap 127.0.0.1:5000 for snappass.atozcc.net, the link works fine.  I just need Redis/SnapPass to spit out snappass.atozcc.net.  Any ideas?

**Comment by leftorbit23** [comment]
I just submitted a pull request that allows you to replace the URL host using an environment variable.

**Comment by azaloum90** [comment]
Oh awesome, thanks for the response and work!  Will the docker image get this update as well?  Or do I need to switch a PIP install?

Thanks!
Adam

**Comment by azaloum90** [comment]
Oh, and where is the configuration variables file within a docker pull?  Haven't been able to locate it.

**Comment by leftorbit23** [comment]
You can download the updated code from my repository.

git clone -b  add-host-env-var --single-branch  https://github.com/leftorbit23/snappass.git

Add the HOST environment variable to docker-compose.yml

HOST=snappass.atozcc.net

Also remove the NO_SSL variable if you're using https

**Comment by azaloum90** [comment]
What about using a reverse proxy that is running SSL and doing forwarding to port 5000?  Does the NO_SSL variable need to be set to false or true?

**Comment by ApolloDS** [comment]
Generated ont-time URL are always with http://hostname/xyz and not https://hostname/xyz.
I tried setting NO_SSL to false and true.
Setup is a Rev. Proxy in Kubernetes.

How to use https:// urls behind a rev. proxy with the docker image?
