### ISSUE TITLE
Mock redis for tests

### ISSUE THREAD

**Issue by nichochar** [pinterest/snappass#25]
Right now, I believe our CI tool is mocking redis. I would like to investigate replacing it either with a simple in memory `get/set` redis mock, or a maybe using a librry like [fakeredis](https://pypi.python.org/pypi/fakeredis)

**Comment by samueldg** [comment]
Also worth considering https://pypi.python.org/pypi/redislite, which is quite mature.

**Comment by OriHoch** [comment]
why do you need a mock redis? why not use a real redis?

`docker run -d -p 6379:6379 redis`

**Comment by nichochar** [comment]
Thanks for the suggestion @OriHoch , actually I run redis very easily on my mac with `brew services start redis`, the problem isn't running it, it's that I think a good unit test doesn't test the third party dependency (although that integration test is very useful), but the logic of the code it's testing.

I also like the idea of people being able to contribute to the project without having to install docker, redis, or any third party dependency.

**Comment by nichochar** [comment]
Fixed
