### ISSUE TITLE
dead or expired URL goes to 404 page

### ISSUE THREAD

**Issue by rgarciapds** [pinterest/snappass#31]
I an not sure if this is an issue, a config issue on my part, or if it was the intent of the developer but i thought I would report here just in case.
If a link has already been used or is expired it goes to a generic 404 page. 
Centos 7.2
Apache/2.4.6 (reverse proxy)
Python 2.7.5
pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
Redis server v=2.6.17

```
Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

Would it be better if snappass instead showed a page informing them that the link was either expired, wrong, or already used? If it is an config issue on my part or the devs intent let me know. Thank you.

**Comment by jameswthorne** [comment]
Right now, this is as designed. A Jinja2 template could be added to be display a more informative 404 page instead of the Python web server returning its default 404 page.

**Comment by rgarciapds** [comment]
Thanks James, I appreciate the response!
