### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by ichait-bgl** [pinterest/snappass#387]
With the recent changes to [requirements.txt](https://github.com/pinterest/snappass/commits/master/requirements.txt) on 3rd August 2024, we're seeing the following errors when running in Kubernetes:
```
ValueError: invalid literal for int() with base 10: 'tcp://172.20.105.225:5000'
sys.exit(load_entry_point('snappass==1.6.2', 'console_scripts', 'snappass')())
File "/usr/local/lib/python3.8/site-packages/snappass-1.6.2-py3.8.egg/snappass/main.py", line 63, in inner
return fn(*args, **kwargs)
app.run(host=os.environ.get('SNAPPASS_BIND_ADDRESS', '0.0.0.0'),
File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 597, in run
port = int(port)
```
Rolling back to a docker image built prior to that time works fine.

Kubernetes 1.30.2

**Comment by shreyrishabh** [comment]
As a workaround, you can pass env variable SNAPPASS_PORT = 5000 in deployment manifest. It is working for me.

**Comment by ichait-bgl** [comment]
Thanks @shreyrishabh ! - will give that a try.

**Comment by ichait-bgl** [comment]
@shreyrishabh - works a treat! Thanks very much.
