### ISSUE TITLE
Intermediary password link page

### ISSUE THREAD

**Issue by jameswthorne** [pinterest/snappass#42]
Hey folks,

I've been maintaining my own fork of snappass for sometime, but I am currently in the process of rebasing all of my changes on top of the latest changes in pinterest/snappass.

One of the features I added is an intermediary password link page. This was added because I quickly discovered services like Facebook Chat, Slack, etc. would issue a GET request on any URL pasted into the input box. Because of the way snappass is designed, the moment the GET request is issued, the password link is rendered useless and the intended recipient cannot see it. An intermediary password link page solves this.

Is this a feature you all would like to incorporate?

**Comment by nichochar** [comment]
Hi 👋,
This is 100% something I would like to incorporate. I believe a tool like this one is only effective if you can use it in a seamless manner, which means in our case through slack (maybe other intermediary clients).
I have been thinking about how to add a clever integration but don't have a good solution yet, so I'm very excited to hear about yours. Could you elaborate on how it works, or even better, submit the PR so we can begin the conversation?

Thanks

**Comment by jameswthorne** [comment]
My implementation is less clever and more simple.

I simply added another page in the process. Instead of the password being revealed when the end user navigates to http://localhost:5000/7faa2e69c31f40b587db8617806c8741, that page now displays another link: http://localhost:5000/7faa2e69c31f40b587db8617806c8741/reveal. Once the user goes to the URL with /reveal appended, the password is displayed and the redis key is deleted.

This solves the issue and if an end user knows how snappass works, they can always append /reveal to any URL to go directly to the password instead.

Here's what the intermediary page looks like:

http://public.thornelabs.net/snappass-intermediary-page-get-password-link.png

PR incoming.

**Comment by jameswthorne** [comment]
PR submitted: https://github.com/pinterest/snappass/pull/43

**Comment by jameswthorne** [comment]
Closing in favor of using #46 method.
