### ISSUE TITLE
is there a live demo so we could see?

### ISSUE THREAD

**Issue by tvvocold** [pinterest/snappass#5]

**Comment by tvvocold** [comment]
i had install it in a debian vps and it's cool!
but anybody had run it in openshift? ( a free PAAS)

**Comment by tvvocold** [comment]
here is what i try:
1,install [rhc tools](https://developers.openshift.com/en/managing-client-tools.html)

**Comment by tvvocold** [comment]
i had run to a trouble with redis and fixed by apt-get install redis-server，maybe it's a samething?

**Comment by yongwen** [comment]
@tvvocold thanks to @samueldg who dockerized snappass. Now you should be able to easily start up your local snappass server and play with it. just follow this simple step:
1. install docker/docker-compose
2. docker build -t snappass .
3. docker-compose up -d
then point your browser to http://localhost:5000
That's it.
