### ISSUE TITLE
Feature : Add view limit possibility and date limit

### ISSUE THREAD

**Issue by pydubreucq** [pinterest/snappass#56]
Hi,
Nice tools, thanks :)
A nice feature could be to add the possibility to config a view limit number and a date limit.
Best Regards,
Pierre-Yves Dubreucq

**Comment by nichochar** [comment]
Bonjour,
Could you elaborate on what you think these features would look like.

*Date limit*: it is my understanding that giving the password a time to live is the same thing as a date limit, so this already exists

*Limit number*: We could discuss it, but it is my opinion that this goes against the design of the password share. If you need multiple people to see the same password, I think it's better to generate multiple one time view passes. To automate this, [we are looking at the implementation of an api](https://github.com/pinterest/snappass/pull/51)

**Comment by nichochar** [comment]
Closing as this thread seems inactive, feel free to ask another question.
