### ISSUE TITLE
pypi credentials

### ISSUE THREAD

**Issue by nichochar** [pinterest/snappass#60]
Hi @davedash , could you set me up with [pypi](https://pypi.python.org/pypi/snappass/0.1.0) permissions on this repository? 

My username is **nichochar**

Thanks!

**Comment by davedash** [comment]
Sure, can you get me permissions on this repo?

**Comment by jparise** [comment]
@davedash I just added you as a collaborator.

**Comment by davedash** [comment]
Thanks @jparise .  @nichochar should be able to push to pypi.

**Comment by nichochar** [comment]
Thanks 🙏 @davedash
