### ISSUE TITLE
Deprecate Python <2.7, <3.4 

### ISSUE THREAD

**Issue by samueldg** [pinterest/snappass#76]
Currently, SnapPass supports Python 2.6, 3.3, 3.4, 3.5 and 3.6.
Two of these, namely 2.6 and 3.3, have been retired for a while now.

See [Python 2.6](https://www.python.org/download/releases/2.6.9/) (released on 2013-10-29):

> With the 2.6.9 release, and five years after its first release, the Python 2.6 series is now officially retired. All official maintenance for Python 2.6, including security patches, has ended.

Similarly, [Python 3.3.7](https://www.python.org/downloads/release/python-337/) (released on 2017-09-19):

> Python 3.3.x has reached end-of-life. This is its final release.

A consequence of that, for example, is the lack of 2.6/3.3 Docker images on [library/python](https://hub.docker.com/_/python/).

IMO it would be easier to maintain this package without going as far back in the Python versions, e.g. mocking redis for tests would be easy with [redislite](https://pypi.python.org/pypi/redislite/3.2.311) which doesn't support Python 2.6.

The code could also be simplified, e.g. I vaguely remember trying to use [unittest.TestCase.assertIn](https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertIn), but having to revert back because it didn't exist in one Python version.

Also, it's kind of paradoxical for a security product to still support unmaintained Python versions. 

Anyways, I guess the list could go on, but that's basically my point. If you guys are interested, I'd be willing to make the change, and even address some of the remaining issues, which would be less of a pain.

**Comment by nichochar** [comment]
Agreed, see referenced PR https://github.com/pinterest/snappass/pull/78
