### ISSUE TITLE
Enable Python 3.7 in Travis build when available

### ISSUE THREAD

**Issue by samueldg** [pinterest/snappass#91]
Python 3.7 support was added in https://github.com/pinterest/snappass/pull/90, but at the time of writing this, Travis CI does not support Python 3.7.

Once https://github.com/travis-ci/travis-ci/issues/9815 is implemented, we should uncomment the [Python 3.7 line from the `travis.yml` file](https://github.com/samueldg/snappass/blob/867dc24f83564c16c7820318f3346ade91218ce5/.travis.yml#L7)

**Comment by jparise** [comment]
This was addressed by #90.
